# -*- mode: ruby -*-
# vi: set ft=ruby :

#########################
$CPU = 2
$MEMORY = 2048
$CPUEXECUTIONCAP = 50
$IP = "192.168.0.4"
$BASEOS = "file://builds/{{ cookiecutter.vm_name }}-virtualbox.box"
$SSH=2004
#########################

Vagrant.configure("2") do |config|

  # VirtualBox.
  config.vm.define "virtualbox" do |virtualbox|
    virtualbox.vm.hostname = "{{ cookiecutter.vm_name }}"
    config.vm.synced_folder '.', '/vagrant'
    virtualbox.vm.box = $BASEOS

    config.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = $MEMORY
      v.cpus = $CPU
      v.customize ["modifyvm", :id, "--cpuexecutioncap", $CPUEXECUTIONCAP]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
      v.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000 ]
    end
    
    config.vm.network "private_network", ip: $IP
    config.vm.network "forwarded_port", guest: 22, host: $SSH, id: 'ssh'

    config.vm.provision "shell", inline: "echo Hello, World"
  end

end
